title: quirkshops
author: quansight
email: tony.fast@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  stories in open source
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", ".nox"]
execute:
  execute_notebooks:  "off"
